# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "8192"
     vb.cpus = 6
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y haproxy
  SHELL
end
